#!/bin/bash

# Required for servers using other lang
LANG=en_US.UTF-8

if [ -e "/usr/local/cwpsrv/logs/error_log" ];then
        #daily log
        grep "`date '+%Y/%m/%d' -d '1 day ago'`" /usr/local/cwpsrv/logs/error_log | grep open_basedir && sh /scripts/cwpsrv_rebuild_user_conf
fi
