#!/bin/bash
# CWP Updater script for CWPadmin

# LOG FOLDER CHECK
if [ ! -e "/var/log/cwp" ];then
	mkdir /var/log/cwp
fi

# UPDATE
if [ -e "/usr/bin/curl" ];then
	CHECK_NEW_VERSION=`curl -Ss "http://centos-webpanel.com/webpanel/versions/el7-stable.txt" | awk {'print $1'}`
	CHECK_CURENT_VERSION=`cat /usr/local/cwpsrv/htdocs/resources/admin/version.txt`

	if [[ "$CHECK_NEW_VERSION" -gt "$CHECK_CURENT_VERSION" ]];then
		CWP_FILENAME="cwp-el7-admin-$CHECK_NEW_VERSION.zip"

		cd /usr/local/cwpsrv/htdocs
		wget "static.cdn-cwp.com/files/cwp/el7/$CWP_FILENAME"
		chattr -i -R /usr/local/cwpsrv/htdocs/admin 2> /dev/null

		unzip -o $CWP_FILENAME
		rm -f $CWP_FILENAME
		chattr +i -R /usr/local/cwpsrv/htdocs/admin 2> /dev/null

		echo "CWPadmin DESIGN Updated to $CHECK_NEW_VERSION" >> /var/log/cwp/cwp_update.log

	fi

else
	echo "FAILED: CURL not installed, try: yum install curl"
fi
